language: objective-c # Force OS X
rvm: system
cache: bundler
before_install:
  - sudo gem install bundler
  - HOMEBREW_DEVELOPER=1 brew update
  - ln -s . $(brew --repo)/Library/Taps/homebrew/homebrew-bundle
script:
  - brew style homebrew/bundle
  - bundle exec rake
notifications:
  email:
    on_success: never
    on_failure: always
